# Generated by Django 3.0 on 2021-04-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'categoria',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('condicion_civil', models.CharField(max_length=30)),
                ('categoria_idcategoria', models.ForeignKey(db_column='idcascade', on_delete=django.db.models.deletion.CASCADE, to='RegistroSocios.Categoria')),
            ],
            options={
                'verbose_name': 'persona',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('idpuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'puesto',
                'db_table': 'puesto',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('fotoQR', models.ImageField(upload_to='')),
                ('fotorostro', models.ImageField(upload_to='')),
                ('persona_idpersona', models.ForeignKey(db_column='idpersona', on_delete=django.db.models.deletion.CASCADE, to='RegistroSocios.Persona')),
            ],
            options={
                'verbose_name': 'registro',
                'db_table': 'registro',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='puesto_idpuesto',
            field=models.ForeignKey(db_column='idpuesto', on_delete=django.db.models.deletion.CASCADE, to='RegistroSocios.Puesto'),
        ),
    ]
