# Generated by Django 3.0 on 2021-04-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroSocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='categoria_idcategoria',
            field=models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='RegistroSocios.Categoria'),
        ),
    ]
