# Generated by Django 3.0 on 2021-04-13 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroSocios', '0003_persona_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
